### ISSUE TITLE
Model timings

### ISSUE THREAD

**Issue by JonasFrey96** [martius-lab/hitchhiking-rotations#18]
Hi everyone, 
I measured the following steps within the testing of the model:
![image](https://github.com/martius-lab/hitchhiking-rotations/assets/56234378/6078b602-a3f4-4f3b-8148-d635980a5fc6)

You can see the reported results over 100 batches - with the given mean and std.
Most interresting is the step 2 - here we have a big slow-down for SVD (0.2 -07)
The actual model inference is only 0.31.

This is how you associate the time with the config  

All times are given in milliseconds.
```yaml
"r9_svd_geodesic_distance": {
  **shared_trainer_cfg,
  **{
    "preprocess_target": "${u:passthrough}", -> 0.0178
    "postprocess_pred_loss": "${u:procrustes_to_rotmat}", -> 0.748
    "postprocess_pred_logging": "${u:procrustes_to_rotmat}", -> 0.740
    "loss": "${u:geodesic_distance}", -> 0.112
    "model": "${model9}", -> 0.315
  },
},

```

![image](https://github.com/martius-lab/hitchhiking-rotations/assets/56234378/ccd17464-7375-459d-9c89-0a0476bc205e)

```yaml
"r9_geodesic_distance": {
    **shared_trainer_cfg,
    **{
        "preprocess_target": "${u:passthrough}",
        "postprocess_pred_loss": "${u:n_3x3}",
        "postprocess_pred_logging": "${u:procrustes_to_rotmat}",
        "loss": "${u:geodesic_distance}",
        "model": "${model9}",
    },
},
"r6_gso_geodesic_distance": {
    **shared_trainer_cfg,
    **{
        "preprocess_target": "${u:passthrough}",
        "postprocess_pred_loss": "${u:gramschmidt_to_rotmat}",
        "postprocess_pred_logging": "${u:gramschmidt_to_rotmat}",
        "loss": "${u:geodesic_distance}",
        "model": "${model6}",
    },
},
```
